"""Tests for notebook environment locking (the ``uv pip compile`` wrapper).

The offline behaviors are pinned here: empty input, rejecting a malformed dependency
before shelling out, and parsing the pinned specs out of ``uv pip compile`` output. A
real resolution hits the network and is exercised by the higher-level suites, not here.
"""

from __future__ import annotations

import pytest

from elbi_core.errors import DerivationError
from elbi_core.notebook import resolve_lock
from elbi_core.notebook.environment import _parse_pins


def test_resolve_lock_empty_is_empty() -> None:
    assert resolve_lock([]) == []


def test_resolve_lock_rejects_a_malformed_dependency() -> None:
    # A shell-injection-shaped spec is refused before uv is ever invoked.
    with pytest.raises(DerivationError):
        resolve_lock(["evil; rm -rf /"])


def test_parse_pins_extracts_only_the_pinned_specs() -> None:
    output = (
        "# This file was autogenerated by uv\n"
        "certifi==2026.6.17\n"
        "requests==2.34.2\n"
        "    # via -r -\n"
        "urllib3==2.7.0    # via requests\n"
        "--index-url https://pypi.org/simple\n"
    )
    assert _parse_pins(output) == [
        "certifi==2026.6.17",
        "requests==2.34.2",
        "urllib3==2.7.0",
    ]
