"""elbi: author data context as code and serve it to agents over MCP.

The public surface is small and stable:

* :func:`derivation`: register a compute function as a derivation.
* :class:`Dataset`: a logical reference to a named data source.
* :class:`SemanticModel`: a governed semantic model a derivation can consume.
* :class:`Context`: resolved inputs handed to a compute function.
* :class:`Artifact`: the output of a derivation.
* :mod:`serve`: builders for serve contracts (``serve.table()``, ``serve.text()``…).
* :class:`Runner`: execute derivations locally.
* :data:`registry`: the default derivation registry.
"""

from __future__ import annotations

from . import cache, param, serve
from .artifact import Artifact
from .audit import (
    AuditEvent,
    AuditSink,
    ChainedJsonlAuditSink,
    ChainReport,
    JsonlAuditSink,
    NullAuditSink,
    verify_chain,
)
from .authoring import (
    AuthorOutcome,
    AutoCertifyOnVerify,
    CertificationPolicy,
    GoldenCase,
    ManualCertification,
    RequireChecks,
    RequireSoundConclusion,
    RequireSoundContract,
    VerificationResult,
    author,
    certify,
    propose,
    verify,
)
from .cache import CachePolicy
from .certificate import (
    Certificate,
    CertificateIssuer,
    SigningKey,
    certificate_from_run,
    load_issuer,
    load_or_create_key,
    verify_certificate,
)
from .components import (
    is_valid_component,
    search_components,
    stamp_provenance,
    validate_component,
)
from .container import DockerExecutor, DockerReplSession
from .context import Context
from .dashboard import (
    DASHBOARD_SPEC_VERSION,
    Bind,
    DashboardSpec,
    GridPos,
    Interactions,
    Options,
    Page,
    Variable,
    Widget,
    WidgetData,
    initial_variable_state,
    is_valid_dashboard,
    resolve_page,
    resolve_widget,
    validate_dashboard,
)
from .dataset import Dataset
from .derivation import Derivation, derivation
from .errors import (
    AuthorizationError,
    CacheError,
    CertificateError,
    ComponentError,
    ConfigError,
    CycleError,
    DataBindingError,
    DerivationError,
    DuplicateDerivationError,
    ElbiError,
    MissingInputError,
    ParamError,
    SpecValidationError,
    UnknownDerivationError,
)
from .executor import (
    CodeResult,
    Executor,
    InProcessExecutor,
    RoutingExecutor,
    SubprocessExecutor,
)
from .features import (
    FEATURE_STORE_SPEC_VERSION,
    Entity,
    Feature,
    FeatureStore,
    FeatureView,
    InMemoryOnlineStore,
    OnlineStore,
    get_historical_features,
    get_online_features,
    is_valid_feature_store,
    materialize,
    validate_feature_store,
)
from .jobs import (
    InMemoryJobStore,
    Job,
    JobRunner,
    JobState,
    JobStore,
    JobWork,
    new_job_id,
)
from .lineage import LineageEdge, LineageGraph, LineageNode
from .lineage import from_registry as lineage_from_registry
from .metrics import (
    METRIC_SPEC_VERSION,
    Format,
    Metric,
    MetricResult,
    MetricSet,
    compile_metric,
    from_osi,
    is_valid_metric_set,
    resolve_metric,
    to_osi,
    validate_metric_set,
)
from .monitoring import AnomalyVerdict, detect_anomaly
from .orchestration import MaterializationStep, RunResult, asset_status
from .orchestration import materialize as materialize_assets
from .param import Param
from .quality import (
    ClauseResult,
    ColumnProfile,
    Constraints,
    ContractReport,
    DataContract,
    FieldSpec,
    ForeignKey,
    Reference,
    TableSpec,
    Violation,
    profile_columns,
    suggest_contract,
    verify_contract,
)
from .query import QueryResult, query_datasets
from .registry import Registry
from .registry import default_registry as registry
from .retrieval import (
    Bm25Retriever,
    Embedder,
    EmbeddingRetriever,
    HybridRetriever,
    Model2VecEmbedder,
    Retriever,
    default_retriever,
)
from .runner import Runner
from .semantic_model import SemanticModel
from .serve import Serve
from .session import ReplSession, Session, SessionManager
from .session_jobs import submit_code_job
from .spec import SPEC_VERSION, is_valid_manifest, load_schema, validate_manifest
from .structure import StructureMap
from .structure import analyze as analyze_structure
from .verification import (
    CompositeReport,
    MultiverseReport,
    VerificationReport,
    applicable,
    verify_all,
    verify_calibration,
    verify_classification,
    verify_clusters,
    verify_comparison,
    verify_correlation,
    verify_counts,
    verify_did,
    verify_effect,
    verify_equivalence,
    verify_experiment,
    verify_extrapolation,
    verify_fairness,
    verify_forecast,
    verify_groups,
    verify_iv,
    verify_leakage,
    verify_logistic,
    verify_missingness,
    verify_multiverse,
    verify_normality,
    verify_overlap,
    verify_powerlaw,
    verify_prediction,
    verify_proportional_hazards,
    verify_proportions,
    verify_rdd,
    verify_regression,
    verify_reliability,
    verify_sensitivity,
    verify_stationarity,
    verify_survival,
    verify_trend,
)

__version__ = "0.1.0"

__all__ = [
    "DASHBOARD_SPEC_VERSION",
    "FEATURE_STORE_SPEC_VERSION",
    "METRIC_SPEC_VERSION",
    "SPEC_VERSION",
    "AnomalyVerdict",
    "Artifact",
    "AuditEvent",
    "AuditSink",
    "AuthorOutcome",
    "AuthorizationError",
    "AutoCertifyOnVerify",
    "Bind",
    "Bm25Retriever",
    "CacheError",
    "CachePolicy",
    "Certificate",
    "CertificateError",
    "CertificateIssuer",
    "CertificationPolicy",
    "ChainReport",
    "ChainedJsonlAuditSink",
    "ClauseResult",
    "CodeResult",
    "ColumnProfile",
    "ComponentError",
    "CompositeReport",
    "ConfigError",
    "Constraints",
    "Context",
    "ContractReport",
    "CycleError",
    "DashboardSpec",
    "DataBindingError",
    "DataContract",
    "Dataset",
    "Derivation",
    "DerivationError",
    "DockerExecutor",
    "DockerReplSession",
    "DuplicateDerivationError",
    "ElbiError",
    "Embedder",
    "EmbeddingRetriever",
    "Entity",
    "Executor",
    "Feature",
    "FeatureStore",
    "FeatureView",
    "FieldSpec",
    "ForeignKey",
    "Format",
    "GoldenCase",
    "GridPos",
    "HybridRetriever",
    "InMemoryJobStore",
    "InMemoryOnlineStore",
    "InProcessExecutor",
    "Interactions",
    "Job",
    "JobRunner",
    "JobState",
    "JobStore",
    "JobWork",
    "JsonlAuditSink",
    "LineageEdge",
    "LineageGraph",
    "LineageNode",
    "ManualCertification",
    "MaterializationStep",
    "Metric",
    "MetricResult",
    "MetricSet",
    "MissingInputError",
    "Model2VecEmbedder",
    "MultiverseReport",
    "NullAuditSink",
    "OnlineStore",
    "Options",
    "Page",
    "Param",
    "ParamError",
    "QueryResult",
    "Reference",
    "Registry",
    "ReplSession",
    "RequireChecks",
    "RequireSoundConclusion",
    "RequireSoundContract",
    "Retriever",
    "RoutingExecutor",
    "RunResult",
    "Runner",
    "SemanticModel",
    "Serve",
    "Session",
    "SessionManager",
    "SigningKey",
    "SpecValidationError",
    "StructureMap",
    "SubprocessExecutor",
    "TableSpec",
    "UnknownDerivationError",
    "Variable",
    "VerificationReport",
    "VerificationResult",
    "Violation",
    "Widget",
    "WidgetData",
    "__version__",
    "analyze_structure",
    "applicable",
    "asset_status",
    "author",
    "cache",
    "certificate_from_run",
    "certify",
    "compile_metric",
    "default_retriever",
    "derivation",
    "detect_anomaly",
    "from_osi",
    "get_historical_features",
    "get_online_features",
    "initial_variable_state",
    "is_valid_component",
    "is_valid_dashboard",
    "is_valid_feature_store",
    "is_valid_manifest",
    "is_valid_metric_set",
    "lineage_from_registry",
    "load_issuer",
    "load_or_create_key",
    "load_schema",
    "materialize",
    "materialize_assets",
    "new_job_id",
    "param",
    "profile_columns",
    "propose",
    "query_datasets",
    "registry",
    "resolve_metric",
    "resolve_page",
    "resolve_widget",
    "search_components",
    "serve",
    "stamp_provenance",
    "submit_code_job",
    "suggest_contract",
    "to_osi",
    "validate_component",
    "validate_dashboard",
    "validate_feature_store",
    "validate_manifest",
    "validate_metric_set",
    "verify",
    "verify_all",
    "verify_calibration",
    "verify_certificate",
    "verify_chain",
    "verify_classification",
    "verify_clusters",
    "verify_comparison",
    "verify_contract",
    "verify_correlation",
    "verify_counts",
    "verify_did",
    "verify_effect",
    "verify_equivalence",
    "verify_experiment",
    "verify_extrapolation",
    "verify_fairness",
    "verify_forecast",
    "verify_groups",
    "verify_iv",
    "verify_leakage",
    "verify_logistic",
    "verify_missingness",
    "verify_multiverse",
    "verify_normality",
    "verify_overlap",
    "verify_powerlaw",
    "verify_prediction",
    "verify_proportional_hazards",
    "verify_proportions",
    "verify_rdd",
    "verify_regression",
    "verify_reliability",
    "verify_sensitivity",
    "verify_stationarity",
    "verify_survival",
    "verify_trend",
]
