"""The ``@derivation`` decorator and the :class:`Derivation` it produces.

A derivation pairs a *compute* function with the declarative metadata that makes
it servable and verifiable: its inputs, its dependencies, and its serve contract.
On definition, the derivation's manifest is validated against the spec, so an
invalid derivation fails loudly at import time, not at serve time.
"""

from __future__ import annotations

import inspect
import textwrap
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from typing import Any, Literal, Union

from .cache import DEFAULT as DEFAULT_CACHE
from .cache import CachePolicy
from .context import Context
from .dataset import Dataset
from .errors import DerivationError
from .param import Param
from .quality.contract import DataContract
from .registry import Registry, active_registry
from .semantic_model import SemanticModel
from .serve import Serve
from .spec import SPEC_VERSION, validate_manifest

#: An input is a raw dataset, another derivation's output, or a governed semantic model.
InputSpec = Union[Dataset, SemanticModel, "Derivation"]

ComputeFn = Callable[[Context], Any]

#: Who authored a derivation: human-authored code, or agent-generated source.
Origin = Literal["human", "agent"]

#: Lifecycle/trust state. Only ``certified`` derivations are served to agents.
Status = Literal["proposed", "certified"]


def _refuse_in_process(ctx: Context) -> Any:
    """The ``compute`` of an agent-authored derivation: never run in-process.

    Agent-generated source is untrusted; it carries its logic in ``source`` and
    must run under an isolating executor. Calling it directly is a bug, so it
    fails loudly rather than executing generated code in the host process.
    """
    raise DerivationError(
        "agent-authored derivation cannot run in-process; "
        "execute it under a sandbox executor"
    )


@dataclass(frozen=True)
class Derivation:
    """A named transformation over data.

    Construct via the :func:`derivation` decorator rather than directly. A
    derivation with no ``serve`` contract is *internal*: it can be consumed by
    other derivations but is not exposed to agents over MCP.
    """

    name: str
    compute: ComputeFn
    serve: Serve | None = None
    inputs: Mapping[str, InputSpec] = field(default_factory=dict)
    params: Mapping[str, Param] = field(default_factory=dict)
    depends_on: tuple[str, ...] = ()
    description: str | None = None
    cache: CachePolicy = DEFAULT_CACHE
    origin: Origin = "human"
    status: Status = "certified"
    source: str | None = None
    claim: Mapping[str, Any] | None = None
    #: The data contract the derivation's output must satisfy. When present,
    #: certification runs the contract checker on the output and certifies only when it
    #: is sound (the data-validity gate, complementary to ``claim``'s soundness gate).
    contract: DataContract | None = None
    #: Third-party packages the agent-authored source imports (PEP 508 names, e.g.
    #: ``scikit-learn``). They are provisioned into the sandbox when the derivation
    #: runs, so a certified derivation can use numpy/pandas/sklearn. Empty for
    #: stdlib-only and human-authored derivations. An execution detail, not part of the
    #: logical manifest, so it does not appear in :meth:`to_manifest`.
    deps: tuple[str, ...] = ()

    @property
    def is_served(self) -> bool:
        """Whether this derivation is exposed to agents (has a serve contract)."""
        return self.serve is not None

    @property
    def is_certified(self) -> bool:
        """Whether this derivation is approved for serving to agents."""
        return self.status == "certified"

    @property
    def is_agent_authored(self) -> bool:
        """Whether this derivation was generated by an agent (untrusted source)."""
        return self.origin == "agent"

    def to_manifest(self) -> dict[str, Any]:
        """Serialize to a spec-conformant manifest dict."""
        manifest: dict[str, Any] = {
            "specVersion": SPEC_VERSION,
            "kind": "Derivation",
            "name": self.name,
        }
        # Emit provenance only when it departs from the (human, certified)
        # default, keeping the common manifest minimal.
        if self.origin != "human":
            manifest["origin"] = self.origin
        if self.status != "certified":
            manifest["status"] = self.status
        if self.serve is not None:
            manifest["serve"] = self.serve.to_manifest()
        if self.description:
            manifest["description"] = self.description
        if self.inputs:
            manifest["inputs"] = {
                key: _input_to_manifest(value) for key, value in self.inputs.items()
            }
        if self.params:
            manifest["params"] = {
                key: value.to_manifest() for key, value in self.params.items()
            }
        if self.depends_on:
            manifest["dependsOn"] = list(self.depends_on)
        # The conclusion this derivation asserts, as verification column roles; when
        # present, certification gates it through the oracle (see authoring.verify).
        if self.claim:
            manifest["claim"] = dict(self.claim)
        # The data contract the output must satisfy; embedded as a full DataContract
        # manifest and gated at certification (see authoring.verify).
        if self.contract is not None:
            manifest["contract"] = self.contract.to_manifest()
        return manifest

    def dataset_inputs(self) -> dict[str, Dataset]:
        """The subset of inputs that are raw datasets, keyed by input name."""
        return {
            key: value
            for key, value in self.inputs.items()
            if isinstance(value, Dataset)
        }

    def derivation_inputs(self) -> dict[str, Derivation]:
        """The subset of inputs that are upstream derivations, keyed by name."""
        return {
            key: value
            for key, value in self.inputs.items()
            if isinstance(value, Derivation)
        }

    def semantic_model_inputs(self) -> dict[str, SemanticModel]:
        """The subset of inputs that are governed semantic models, keyed by name."""
        return {
            key: value
            for key, value in self.inputs.items()
            if isinstance(value, SemanticModel)
        }


def derivation(
    func: ComputeFn | None = None,
    *,
    name: str | None = None,
    serve: Serve | None = None,
    inputs: Mapping[str, InputSpec] | None = None,
    params: Mapping[str, Param] | None = None,
    depends_on: list[str] | tuple[str, ...] | None = None,
    description: str | None = None,
    cache: CachePolicy | None = None,
    origin: Origin = "human",
    status: Status = "certified",
    contract: DataContract | None = None,
    claim: Mapping[str, Any] | None = None,
    registry: Registry | None = None,
) -> Derivation | Callable[[ComputeFn], Derivation]:
    """Register a compute function as a derivation.

    Usage::

        @derivation(inputs={"sales": Dataset("sales")}, serve=serve.table())
        def churn_risk(ctx: Context) -> Artifact: ...

    Args:
        func: The compute function (supplied implicitly by the decorator).
        name: Derivation name. Defaults to the function name.
        serve: The serve contract. Optional; a derivation with no serve contract
            is *internal* (usable as an input to other derivations, not exposed to
            agents over MCP).
        inputs: Map of input name to a :class:`Dataset`, an upstream
            :class:`Derivation`, or a
            :class:`~elbi.semantic_model.SemanticModel`.
        params: Map of parameter name to a :class:`~elbi.param.Param`.
            Supplied by the agent at run time and exposed as the served tool's
            input schema.
        depends_on: Extra ordering-only dependencies, by name. Dependencies on
            derivation inputs are inferred automatically.
        description: Overrides the docstring-derived description.
        cache: Cache policy (see :mod:`~elbi.cachepolicy`). Defaults to
            content-addressed caching; pass ``cache.never()`` for derivations that
            read untracked state.
        origin: Provenance: ``"human"`` (default) or ``"agent"`` for a derivation
            authored by the agent-authoring loop.
        status: Lifecycle: ``"certified"`` (default) or ``"proposed"``. A
            ``"proposed"`` derivation is not served until certified.
        contract: A :class:`~elbi.quality.contract.DataContract` the output
            must satisfy. When set, certification runs the contract checker on the
            output and certifies only a sound result (see :func:`authoring.verify`).
        claim: An optional effect claim the output asserts, as a role→column mapping
            (e.g. ``{"x": ..., "y": ..., "controls": [...]}``). When set, verification
            re-checks it and the derivation is served only if it certifies sound.
            Opt-in: a derivation with no claim is not oracle-gated.
        registry: Registry to register into. Defaults to the active registry
            (the shared default, unless discovery has set another).

    Returns:
        The constructed :class:`Derivation`.
    """
    target_registry = registry if registry is not None else active_registry()

    def wrap(fn: ComputeFn) -> Derivation:
        resolved_inputs: Mapping[str, InputSpec] = dict(inputs or {})
        inferred = tuple(
            dep.name for dep in resolved_inputs.values() if isinstance(dep, Derivation)
        )
        explicit = tuple(depends_on or ())
        combined = tuple(dict.fromkeys((*inferred, *explicit)))

        if contract is not None:
            contract.validate()
        derivation_obj = Derivation(
            name=name or fn.__name__,
            compute=fn,
            serve=serve,
            inputs=resolved_inputs,
            params=dict(params or {}),
            depends_on=combined,
            description=description if description is not None else _docstring(fn),
            cache=cache if cache is not None else DEFAULT_CACHE,
            origin=origin,
            status=status,
            contract=contract,
            claim=dict(claim) if claim is not None else None,
        )
        # Fail at definition time if the derivation is not spec-conformant.
        validate_manifest(derivation_obj.to_manifest())
        target_registry.register(derivation_obj)
        return derivation_obj

    if func is not None:
        return wrap(func)
    return wrap


def _input_to_manifest(value: InputSpec) -> dict[str, Any]:
    if isinstance(value, Dataset):
        return {"kind": "dataset", "ref": value.name}
    if isinstance(value, SemanticModel):
        return {"kind": "semantic_model", "ref": value.name}
    return {"kind": "derivation", "ref": value.name}


def _docstring(fn: ComputeFn) -> str | None:
    doc = inspect.getdoc(fn)
    if not doc:
        return None
    return textwrap.shorten(doc.strip().splitlines()[0], width=4096, placeholder="…")
